### ISSUE TITLE
[Bug Report] mpvue组件中getCropperImage缺少参数

### ISSUE THREAD

**Issue by laravuel** [we-plugin/we-cropper#100]
### we-cropper 版本
1.3.4

### 对应工具或者iOS或者Andriod的版本号
微信开发者工具

### 微信版本号
微信开发者工具

### 重现步骤
mpvue组件中getCropperImage缺少参数。

![mpvue组件](https://user-images.githubusercontent.com/12763586/53676477-bd20e780-3cdd-11e9-9316-049a27944e74.png)

getCropperImage定义位置

![default](https://user-images.githubusercontent.com/12763586/53676485-db86e300-3cdd-11e9-8541-c631b8ab8b0e.png)

### 期待的行为
希望修正下，谢谢！
`wecropper.getCropperImage({ original: true })`

### 实际的行为
这样在mpvue中通过$refs拿到的wecropper实例，getCropperImage没法加参数。
只能这样：
`wecropper._wecropper.getCropperImage({ original: true })`

**Comment by dlhandsome** [comment]
已修复
https://github.com/we-plugin/we-cropper/blob/master/packages/mpvue-cropper/mpvue-cropper.vue#L78
