### ISSUE TITLE
[Bug Report] .wecropper.getCropperImage({original:true})得到的并不是原图

### ISSUE THREAD

**Issue by saishang** [we-plugin/we-cropper#101]
### we-cropper 版本
1.3.4

### 对应工具或者iOS或者Andriod的版本号
Android 8.0.0

### 微信版本号
7.0.3

### 重现步骤
将.wecropper.getCropperImage({original:true}) 得到的并不是原图，而是超过原图尺寸很多的图片

### 期待的行为
.wecropper.getCropperImage({original:true})  如何能得到原图尺寸的图片

### 实际的行为
期望裁切一个2000像素宽的图片  无缩放  得到的也是2000像素宽的图片

**Comment by zhanshu233** [comment]
猜测也许是位深度的原因，我的图片位深度裁切前是24，裁切后是32，变大了好多倍

**Comment by dlhandsome** [comment]
```javascript
wecropper.getCropperImage({
   destWidth: 1000,
   destHeight: 1000 // 自己按比例计算一下 
}).then(path => {
  // Todo ...
}) 
```
```getCropperImage```中 ```options``` 参数是继承 ```wx.canvasToTempFilePath``` 的 [详情](https://we-plugin.github.io/we-cropper/#/api?id=wecroppergetcropperimageoptcallback)
