### ISSUE TITLE
[Feature Request] 增加对taro的插件支持

### ISSUE THREAD

**Issue by kalsolio** [we-plugin/we-cropper#109]
### 描述
裁切功能经常遇到, 但是整合难度感觉比较大, 官方是否有计划支持taro

**Comment by dlhandsome** [comment]
有计划

**Comment by dlhandsome** [comment]
https://github.com/we-plugin/we-cropper/tree/master/packages/miniprogram-cropper

目前已支持原生自定义组件，可以在 taro 中使用
