### ISSUE TITLE
裁切生成的图片尺寸问题

### ISSUE THREAD

**Issue by Richard-Chan** [we-plugin/we-cropper#11]
1. 在微信web开发工具上，裁切出来的图片尺寸有点Bug，在使用cutInside功能，切出来的图片被压成了设定尺寸的一半高；
2. 在真机上切出来的图，实际是2倍尺寸，例如设定裁切100x100，切出来保存的尺寸是200x200像素，应该是px 和 rpx 没有很好的限定

感谢作者，希望越做越好

**Comment by dlhandsome** [comment]
#14
