### ISSUE TITLE
[Bug Report] 1.3.5 getCropperImage()无法获取生成图片

### ISSUE THREAD

**Issue by ZHT131** [we-plugin/we-cropper#115]
### we-cropper 版本
1.3.5

### 对应工具或者iOS或者Andriod的版本号
6.0

### 微信版本号
7.0.3

### 重现步骤
1.3.5 getCropperImage()无法获取生成图片
换回1.3.4版本后正常获取

### 期待的行为
getCropperImage()正常获取生成图片

### 实际的行为
getCropperImage()无法获取生成图片

**Comment by dlhandsome** [comment]
```v1.3.6``` 中修复了这个问题 https://github.com/we-plugin/we-cropper/pull/116 
### Changelog
https://we-plugin.github.io/we-cropper/#/changelog
