### ISSUE TITLE
能发个Taro的Demo吗？我按照文档的操作报错了

### ISSUE THREAD

**Issue by wuweijian1997** [we-plugin/we-cropper#120]
参考的文档链接：https://github.com/we-plugin/we-cropper/tree/master/packages/miniprogram-cropper

错误  编译错误  原生组件文件 D:\SPACE\WebStorm\renqun\src\miniprogram-cropper 不存在！

**Comment by dlhandsome** [comment]
```npm i miniprogram-cropper@1.0.3 -S```

**Comment by sunlei4076** [comment]
[这里有个demo可以](https://github.com/zyh9/taro-apps/blob/master/src/pages/upload/index.js)
