### ISSUE TITLE
[Bug Report] mpvue 的版本落后了

### ISSUE THREAD

**Issue by zaxlct** [we-plugin/we-cropper#124]
### we-cropper 版本
1.3.7

### 对应工具或者iOS或者Andriod的版本号
无

### 微信版本号
无

### 重现步骤
无

### 期待的行为
希望 mpvue 版本保持更新

### 实际的行为
无

**Comment by dlhandsome** [comment]
done https://github.com/we-plugin/we-cropper/commit/24d80713740bd06d37208c801548e2a9577e5d3a
