### ISSUE TITLE
请问你解决了吗？我现在要动态改变裁剪框的大小，从缓存拿到我需要的宽高，放到page   data里边、裁剪框会变得特别大或特别小

### ISSUE THREAD

**Issue by lylovexm** [we-plugin/we-cropper#129]
请问你解决了吗？我现在要动态改变裁剪框的大小，从缓存拿到我需要的宽高，放到page   data里边、裁剪框会变得特别大或特别小

_Originally posted by @ZhuRuiHeng in https://github.com/we-plugin/we-cropper/issues/29#issuecomment-353406438_

**Comment by ZhuRuiHeng** [comment]
@lylovexm 
![1](https://user-images.githubusercontent.com/28189090/58066837-a17efc00-7bbd-11e9-8d91-3245fa62558a.png)

**Comment by lylovexm** [comment]
您好  mpvue-cropper 组件不需要修改吗？  我的是在小程序中  劳烦你解答 谢谢




------------------ 原始邮件 ------------------
发件人: "ZhuRuiHeng"<notifications@github.com>;
发送时间: 2019年5月21日(星期二) 中午11:43
收件人: "we-plugin/we-cropper"<we-cropper@noreply.github.com>;
抄送: "头条新闻"<1478481825@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [we-plugin/we-cropper] 请问你解决了吗？我现在要动态改变裁剪框的大小，从缓存拿到我需要的宽高，放到page   data里边、裁剪框会变得特别大或特别小 (#129)




@lylovexm

**Comment by ZhuRuiHeng** [comment]
@lylovexm 我用的时候是原生小程序，直接修改的这个文件https://github.com/we-plugin/we-cropper/blob/master/example/avatarUpload/upload/upload.js

**Comment by lylovexm** [comment]
好 谢谢




------------------ 原始邮件 ------------------
发件人: "ZhuRuiHeng"<notifications@github.com>;
发送时间: 2019年5月21日(星期二) 中午11:49
收件人: "we-plugin/we-cropper"<we-cropper@noreply.github.com>;
抄送: "头条新闻"<1478481825@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [we-plugin/we-cropper] 请问你解决了吗？我现在要动态改变裁剪框的大小，从缓存拿到我需要的宽高，放到page   data里边、裁剪框会变得特别大或特别小 (#129)




@lylovexm 我用的时候是原生小程序，直接修改的这个文件https://github.com/we-plugin/we-cropper/blob/master/example/avatarUpload/upload/upload.js

**Comment by ZhuRuiHeng** [comment]
@lylovexm 裁剪框会变得特别大或特别小，应该是，比例没有做好，我当时是要保证图片不变形，就要计算图片的宽高比，宽度>高度时  宽度就乘以某个比例，同理宽度<高度一样

**Comment by lylovexm** [comment]
您好 由于我前端技术很菜  然后现在做的是mpvue他用到了we-cropper但是他又封装了一个方法  dom对象是不存在的 有点不知道怎么操作 您现在给我思路 感谢您




------------------ 原始邮件 ------------------
发件人: "ZhuRuiHeng"<notifications@github.com>;
发送时间: 2019年5月21日(星期二) 中午11:54
收件人: "we-plugin/we-cropper"<we-cropper@noreply.github.com>;
抄送: "头条新闻"<1478481825@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [we-plugin/we-cropper] 请问你解决了吗？我现在要动态改变裁剪框的大小，从缓存拿到我需要的宽高，放到page   data里边、裁剪框会变得特别大或特别小 (#129)




@lylovexm 裁剪框会变得特别大或特别小，应该是，比例没有做好，我当时是要保证图片不变形，就要计算图片的宽高比，宽度>高度时  宽度就乘以某个比例，同理宽度<高度一样
