### ISSUE TITLE
[Bug Report] 包裹整个裁剪框的黑色背景颜色如何修改？

### ISSUE THREAD

**Issue by kongxubihai** [we-plugin/we-cropper#132]
### we-cropper 版本
1.3.7

### 对应工具或者iOS或者Andriod的版本号
小程序开发工具

### 微信版本号
7.0

### 重现步骤
无

### 期待的行为
希望可以通过修改源码等方式去修改黑色背景框。

### 实际的行为
黑色背景框不知如何修改

**Comment by dlhandsome** [comment]
https://github.com/we-plugin/we-cropper/blob/master/dist/we-cropper.wxml#L8
可以在模板中修改 background 属性
