### ISSUE TITLE
【Picture quality】After clipping the picture on the mobile side, it looks very blurred on the PC side.

### ISSUE THREAD

**Issue by YaroED** [we-plugin/we-cropper#136]

**Comment by YaroED** [comment]
【Picture quality】
【图片质量堪忧】

#After clipping the picture on the mobile side, it looks very blurred on the PC side.
#在移动端裁剪完图片后，在PC端上显得很模糊。

#It is hoped that the space of the canvas can be reduced and the clarity of the cavas drawing can be improved by configuring the canvas and drawing the image and text.
#希望可以通过配置，进行放大画布以及图像文字的绘制，缩小画布的空间，提高cavas绘制出来的清晰度。

**Comment by dlhandsome** [comment]
https://we-plugin.github.io/we-cropper/#/api?id=wecroppergetcropperimageoptcallback

```javascript
getCropperImage({ original: true }).then(path => {
  // Todo
})
```
