### ISSUE TITLE
使用wx:if加载we-corpper组件时，再次加载被裁剪的图片不显示

### ISSUE THREAD

**Issue by JohnNashs** [we-plugin/we-cropper#137]
我在使用wepy开发的时候，需要用父组件中的按钮触发we-corpper组件的显示，其中定义了一个变量为false,we-corpper组件的显示用wx:if来控制，点击父组件的触发按钮触发wx.chooseImage，成功后将图片临时路径url传给we-corpper组件，第一次we-corpper组件显示的时候可以出现被裁剪图片，但是第二次触发，被裁剪图片就不显示了，we-cropper imageLoad事件也没触发

**Comment by kevinlvhsl** [comment]
有修复这个bug吗？ 我也是遇到这样的问题
