### ISSUE TITLE
[Feature Request] 什么时候发布新版本

### ISSUE THREAD

**Issue by ericzpd** [we-plugin/we-cropper#147]
### 描述
已经半年没发布新版本了。master 分支包含了一个允许改版裁剪框的改动，希望能尽快发布 <https://github.com/we-plugin/we-cropper/commit/bc8d7457ef081bc4e6eeaa4d160c3aa483e3a990>

**Comment by dlhandsome** [comment]
已发～可以更新到最新版本

**Comment by dlhandsome** [comment]
https://github.com/we-plugin/we-cropper/releases/tag/mpvue-cropper%400.2.3
