### ISSUE TITLE
给new WeCropper(cropperOpt,this ) 加入第二个参数

### ISSUE THREAD

**Issue by mannymu** [we-plugin/we-cropper#150]
第二个参数，传入当前组件的 this ， 方便在自定义组件中嵌套。
修改点：
![image](https://user-images.githubusercontent.com/15630104/69321297-c6901c80-0c7d-11ea-9203-c604190a13a5.png)

创建 画布的时候使用：
![image](https://user-images.githubusercontent.com/15630104/69321332-da3b8300-0c7d-11ea-85db-3dafc08230b8.png)

**Comment by dlhandsome** [comment]
感谢建议，这里本身是支持在自定义组件中使用的，文档中没有注明。

可以在构造器参数中自定义设置 canvas 容器的上下文:

new WeCropper({
// ... other options
// 用于拖拽缩放的画布上下文
ctx: wx.createCanvasContext(id, this),
// 用于生成图片的画布上下文
targetCtx: wx.createCanvasContext(targetId, this)
})
