### ISSUE TITLE
上传图片我设置sizeType只能是原图后，图片如果太大（2M）,会显示不出来

### ISSUE THREAD

**Issue by 03128crz** [we-plugin/we-cropper#18]
`
wx.chooseImage({
			count: 1, // 默认9
			sizeType: ['original'], // 可以指定是原图还是压缩图，默认二者都有
			sourceType: ['album', 'camera'], // 可以指定来源是相册还是相机，默认二者都有
			success (res) {
				const src = res.tempFilePaths[0]
				//  获取裁剪图片资源后，给data添加src属性及其值
				self.wecropper.pushOrign(src)
			}
		})

`

**Comment by dlhandsome** [comment]
#2
