### ISSUE TITLE
图片上传之后怎么变成加了个红色滤镜一样？

### ISSUE THREAD

**Issue by whisper12** [we-plugin/we-cropper#24]
RT

**Comment by dlhandsome** [comment]
没有遇到过这种情况，show me your code and sreenshot?

**Comment by whisper12** [comment]
用的是你demo里的上传头像那个demo
返回来的地址显示是正常的，但是上传之后到后台的图片就加上了滤镜

**Comment by dlhandsome** [comment]
返回的地址显示正常的话那插件是没问题的，你检查下上传后台是不是出问题了
