### ISSUE TITLE
裁剪的尺寸   不能在onload里面指定么？

### ISSUE THREAD

**Issue by charliesong** [we-plugin/we-cropper#29]
现在都是全局变量写死的  如果要在onload里面  获得需要裁剪的宽高，肿么办呢？

**Comment by dlhandsome** [comment]
裁剪框宽度：```$instance.cut.width```
裁剪框高度：```$instance.cut.height```
```$instance```代表插件的实例

**Comment by ZhuRuiHeng** [comment]
请问你解决了吗？我现在要动态改变裁剪框的大小，从缓存拿到我需要的宽高，放到page   data里边、裁剪框会变得特别大或特别小

**Comment by ZhuRuiHeng** [comment]
看了你的实验室，我想要的是局部裁剪，裁剪大小的参数是传进去的，裁剪框会很大或很小，就是长方形或其他非正方形的形状

**Comment by umeitime** [comment]
@ZhuRuiHeng 态修改裁切宽高，你实现了没？

**Comment by ZhuRuiHeng** [comment]
实现了，现在在路上，等明天晚上你提醒我下，我发你看下


| |
远航
邮箱：18749830459@163.com
|

签名由 网易邮箱大师 定制

在2018年02月08日 16:05，June 写道：

@ZhuRuiHeng 态修改裁切宽高，你实现了没？

**Comment by dlhandsome** [comment]
#44

**Comment by ZhuRuiHeng** [comment]
可以指定，在onload里边，初始化的时候把尺寸放进去




| |
远航
邮箱：18749830459@163.com
|

签名由 网易邮箱大师 定制

在2018年02月09日 10:39，Sail 写道：

Closed #29.

**Comment by umeitime** [comment]
@ ZhuRuiHeng onLoad 里面可以修改的，我知道，你只要在new WeCrooper之前都是可以的，但是我想动态修改

**Comment by ZhuRuiHeng** [comment]
我是页面传参传过来的，裁剪尺寸需要什么就传过来，这样动态改变的
onLoad(option) {
// do something
const device = wx.getSystemInfoSync()
const width = device.windowWidth
const height = device.windowHeight - 50;
console.log('option:', option);
console.log("width:", option.width);
let w = width / option.width;
let h = height / option.height;
let width1 = '';
let height1 = '';
if (w < 1 || h < 1) {
if (w < h) {
width1 = width;
height1 = parseInt(option.height * w);
} else {
height1 = height;
width1 = parseInt(option.width * h);
}
}else{
width1 = wx.getStorageSync('width')
height1 = wx.getStorageSync('height')
}
const { cropperOpt } = this.data;
const src = option.src;
this.setData({
cropperOpt: {
id: 'cropper',
width,
height,
scale: 2,
zoom: 8,
cut: {
x: parseInt((width - width1*.8)/2),
y: parseInt((height - height1 * .8) / 2),
width: parseInt(width1 * .8),
height: parseInt(height1 * .8)
},
src: option.src
}
})


if (src) {
// Object.assign(cropperOpt, { src })
const { cropperOpt } = this.data
new weCropper(cropperOpt)
.on('ready', function (ctx) {
console.log(`wecropper is ready for work!`)
})
.on('beforeImageLoad', (ctx) => {
console.log(`before picture loaded, i can do something`)
console.log(`current canvas context:`, ctx)
wx.showToast({
title: '上传中',
icon: 'loading',
duration: 20000
})
})
.on('imageLoad', (ctx) => {
console.log(`picture loaded`)
console.log(`current canvas context:`, ctx)
wx.hideToast()
})
}
}

在 2018-02-11 17:57:06，"June" <notifications@github.com> 写道：


@ ZhuRuiHeng onLoad 里面可以修改的，我知道，你只要在new WeCrooper之前都是可以的，但是我想动态修改

**Comment by heyhodz** [comment]
我想问一下就是改变裁剪框的位置怎么改变啊

**Comment by tangdaibao** [comment]
你好，请问一下如何将裁剪框改变成长方形，设置宽高不行
![image](https://user-images.githubusercontent.com/44692440/71237763-63a5aa00-233d-11ea-9c06-5b08a0dfc648.png)打印出来是这样
![image](https://user-images.githubusercontent.com/44692440/71237803-7c15c480-233d-11ea-9990-31a66f213276.png)永远都是正方形
