### ISSUE TITLE
手动添加水印时，需要移动图片才能添加成功

### ISSUE THREAD

**Issue by baiwuriver** [we-plugin/we-cropper#3]
【设备】
苹果6

【问题现象】
1、页面添加了一个手动加水印的按钮  
<view
                class="word"
                bindtap="addMark">
            添加水印
        </view>
2、函数定义
addMark() {
    this.wecropper.on('beforeDraw', (ctx) => {
      console.log(`before canvas draw,i can do something`)
      console.log(`current canvas context:`, ctx)
      //  那就尝试在图片上加个水印吧
      ctx.setFontSize(14)
      ctx.setFillStyle('#990033')
      ctx.fillText('@greatwe-cropper', 20, 350)
    })
  },

3、点击添加水印按钮，图片上不能立刻显示水印，移动下图片，水印添加成功，显示正常

在苹果6手机和电脑模拟器上都有这个问题，安卓手机未测试

**Comment by dlhandsome** [comment]
### 插件是采用手势驱动的，有两种情况会触发canvas更新：
- 手指与canvas交互
- 传入图片（通过构造器参数传入或pushOrigin方法传入）

> [on](https://dlhandsome.github.io/we-cropper/#/api?id=wecropperonevent-callback)方法仅起到事件监听的作用，并不会自动触发canvas视图更新

上述例子中，手动点击按钮时开启监听事件，要保证水印立即显示，需要通过[updateCanvas](https://dlhandsome.github.io/we-cropper/#/api?id=wecropperupdatecanvas)方法更新canvas视图：
```javascript
this.wecropper.on('beforeDraw', (ctx) => {
      // 加水印操作
      // ...
})

this.wecropper.updateCanvas()

```
或
```javascript
this.wecropper
.on('beforeDraw', (ctx) => {
      // 加水印操作
      // ...
}) 
.updateCanvas()   // 支持链式调用
```
### 问： 为啥[官方示例](https://dlhandsome.github.io/we-cropper/#/)可以不用调用```updateCanvas()```方法实现立即显示水印
> 答：官方示例中在实例化时即开始事件监听，上传图片时，会触发canvas更新，水印则立即显示。而上述例子中，由于事件监听时序的不确定性，不保证在上传图片之前出现，所以会有这种现象。
