### ISSUE TITLE
ios裁剪图片的时候 确定按钮点击无效，重新选择是可以的

### ISSUE THREAD

**Issue by lingdayan** [we-plugin/we-cropper#31]
ios裁剪图片的时候 确定按钮点击无效，重新选择是可以的，想问问这是因为什么，之前用着是没有问题的

**Comment by dlhandsome** [comment]
看看是不是和 [#30](https://github.com/we-plugin/we-cropper/issues/30)同一个问题？

**Comment by lingdayan** [comment]
我不确定是不是这个问题 但是目前在6.5.22版本上都不行，在ios上,之前微信版本是没有问题的，我这边没有报像#30的那个报错  我是直接没有进到这个getCropperImage()方法

**Comment by wangxwen** [comment]
同遇到这个问题，请问有办法了吗

**Comment by dlhandsome** [comment]
用canvasToTemFilePath方法获取画布中的图片试试 @lingdayan @wangxwen

**Comment by BoleLee** [comment]
[ ios 9.3.5 weChat 6.5.22 ] ```getCropperImage``` 失效；测试了使用 ``` wx.canvasToTempFilePath``` 返回错误信息：```"canvasToTempFilePath:fail no image" ```

 @dlhandsome 你知道怎么解决吗，麻烦告知，Thx

**Comment by dlhandsome** [comment]
https://developers.weixin.qq.com/blogdetail?action=get_post_info&docid=916a39b4d3a49fe130206ab3b5a02c9b&highline=canvas&token=&lang=zh_CN
微信官方的bug，只能等官方修复了

**Comment by BoleLee** [comment]
@dlhandsome 谢谢！刚才也写了个demo测试，确认是小程序 ```wx. canvasToTempFilePath```的问题

**Comment by lingdayan** [comment]
@dlhandsome  我也是尝试了好几次 做了几个demo 确实是小程序 wx. canvasToTempFilePath的问题 总是报错：canvasToTempFilePath:fail no image      抱拳感谢~~

**Comment by wfq1095745112** [comment]
官方貌似修复好了bug了， 但是怎么现在使用是没反应的？

**Comment by BoleLee** [comment]
@wfq1095745112 今天ios更新微信版本[6.5.23]了，新版本此问题已修复

**Comment by dlhandsome** [comment]
#32

**Comment by wumiangithub** [comment]
修复了吗？？  我今天 跟新到[6.6] 了    还是不行啊
