### ISSUE TITLE
小程序官方论坛canvas相关问题跟踪

### ISSUE THREAD

**Issue by dlhandsome** [we-plugin/we-cropper#32]
### [点击查看](https://github.com/dlhandsome/weapp-issue-keyword-track/blob/master/md/list.md)
更新频次：每5分钟

**Comment by beambeam** [comment]
iOS11 中 缩放移动被裁剪对象非常卡顿，但在IOS10就不会，大家也是吗
在Android机也不会卡顿，就是在iOS11 中非常卡顿
微信客户端的版本都是6.6.3最新版的
