### ISSUE TITLE
新增wx.canvasGetImageData接口，是不是已经可以实现获取base64数据了

### ISSUE THREAD

**Issue by mkanako** [we-plugin/we-cropper#38]
能否给支持下😙

**Comment by mkanako** [comment]
查了下原来原生就有getImageData这个方法，不过被小程序阉割了，最近又加上，问题就是怎么把getImageData得到的数据转成base64,没找着

**Comment by dlhandsome** [comment]
可以参考这个[demo](https://github.com/Natumsol/base64)

**Comment by dlhandsome** [comment]
可以考虑内置转换算法

**Comment by mkanako** [comment]
粗看了下，这个demo没错了！
能内置转换那就太爽了😘

**Comment by dlhandsome** [comment]
看看是不是符合要求？[Feature: getCropperBase64](https://we-plugin.github.io/we-cropper/#/api?id=wecroppergetcropperbase64callback)

**Comment by mkanako** [comment]
感谢楼主这么勤快，功能测试ok👍
但是有一个问题，这样转码出来的图片是bmp格式，是最原始的图片数据，没有经过JPEG或png编码，图片数据非常大😂

**Comment by dlhandsome** [comment]
后面应该会慢慢开放的

**Comment by dlhandsome** [comment]
https://github.com/we-plugin/we-cropper/releases/tag/v1.2.0
