### ISSUE TITLE
苹果手机剪切生成的图片及水印模糊

### ISSUE THREAD

**Issue by baiwuriver** [we-plugin/we-cropper#4]
【设备】
苹果6

【问题】
图片剪切后，也添加了水印，保存图片，生成的图片及水印看上去比保存前要模糊

安卓手机未测试

**Comment by dlhandsome** [comment]
已修复https://dlhandsome.github.io/we-cropper/#/changelog?id=v113-2017-6-1

**Comment by yanzhankai** [comment]
楼主解决了没，作者的链接失效了

**Comment by dlhandsome** [comment]
#26
