### ISSUE TITLE
mpvue版本按照您给的实例报错

### ISSUE THREAD

**Issue by xiaowuzei** [we-plugin/we-cropper#52]
按照你给的实例，写到了一个页面，报错信息如下。页面展示的效果是可以上传图片，但是无法裁剪
![image](https://user-images.githubusercontent.com/22762611/39025508-1a9d8e52-447a-11e8-82bf-5dd46676e4ab.png)

**Comment by dlhandsome** [comment]
尝试升级mpvue版本

**Comment by xiaowuzei** [comment]
mpvue相关已经更新到最新版本了，跟webpack有关系么，现在是2.6.1

**Comment by xiaowuzei** [comment]
你这确实有问题，我刚刚新建立的项目也是报同样的错误。不存在版本问题。你可以看看你给的demo再试一下
