### ISSUE TITLE
mpvue 版本裁剪图片无法滚动

### ISSUE THREAD

**Issue by williamJson** [we-plugin/we-cropper#59]
在开发工具上是没问题的，但是在手机上就会出现
Do not have handler in current page: pages/base/imgPicker/main. Please make sure that handler has been defined in pages/base/imgPicker/main, or not use handler with 'v-if'
的错误

**Comment by F-loat** [comment]
感觉你的代码没什么问题，但手机上确实触发的事件有差异，我写的这个 [mpvue-echarts](https://github.com/F-loat/mpvue-echarts) 又是正常的🤔，我再对比下看看

**Comment by F-loat** [comment]
另外你这个目前有个循环引用的错误，解决方式时不把 _we_cropper 赋值到 this 上，直接在 script 内定义一个 _we_cropper 的变量即可

**Comment by dlhandsome** [comment]
@F-loat 感谢，我按照你的方式，直接在 script 内定义一个变量保存 we-cropper 实例，但是并不能解决事件问题，最后参照你写的 mpvue-echats ，在canvas里面加了个 v-if
```html
<canvas
  v-if="canvas"
  :canvasId="canvasId"
  @touchstart="touchstart"
  @touchmove="touchmove"
  @touchend="touchend"
  disable-scroll
  :style="{ width: _width + 'px', height: _height + 'px', background: 'rgba(0, 0, 0, .9)' }">
```
这样事件就正常了

**Comment by F-loat** [comment]
emmm那就比较迷了，我那个 v-if 是因为要使用外部传入的 canvasId 才加的，不过确实之前事件是在 canvas 的上一级元素上触发的，我加了 stop 修饰符也有用，但会导致触摸点属性是普通的那种而不是 canvas 的

**Comment by williamJson** [comment]
@F-loat @dlhandsome 感谢二位的帮助

**Comment by F-loat** [comment]
发现 _we_cropper 这类变量还是直接赋值到 this 上好点，只要不在 data 里声明就不会出错，之前那种做法会导致同时使用多个组件时保存的实例始终是同一个

**Comment by yyuxiang** [comment]
mpvue框架开发的小程序也是能用这个插件进行图片裁剪的,插件样式默认把裁剪按钮定位在画布底部,在模拟器上是正常的。在真机上由于按钮在遮罩层下面,会出现按钮点击没反应和长图会盖住按钮的情况,可以给bottom:-100可解决
