### ISSUE TITLE
mpvue裁剪图片问题

### ISSUE THREAD

**Issue by williamJson** [we-plugin/we-cropper#60]
第一次打开裁剪页面选择图片进行裁剪功能没问题但是会报如下错误
Wed May 30 2018 14:37:46 GMT+0800 (中国标准时间) 关键字保护
console.js:231 Wed May 30 2018 14:37:46 GMT+0800 (中国标准时间) 关键字保护
[publib]:18 should not change the protected attribute __route__
t.warn @ [publib]:18
(anonymous) @ [publib]:18
i @ [publib]:18
i @ [publib]:18
i @ [publib]:18
i @ [publib]:18
i @ [publib]:18
i @ [publib]:18
r @ [publib]:18
value @ [publib]:18
(anonymous) @ index.js:5336
(anonymous) @ index.js:5324
updateDataToMP @ index.js:5360
patch @ index.js:4938
Vue._update @ index.js:2068
updateComponent @ index.js:2166
get @ index.js:2496
Watcher @ index.js:2486
mountComponent @ index.js:2170
(anonymous) @ index.js:5529
onReady @ index.js:5173
(anonymous) @ [publib]:18
z @ [publib]:17
(anonymous) @ [publib]:17
(anonymous) @ [publib]:18
(anonymous) @ [publib]:6
e.(anonymous function) @ [publib]:4
S @ [publib]:1
value @ [publib]:764
(anonymous) @ [VM 39]:1
Script.runInContext @ vm.js:59
runInContext @ vm.js:120
handleEvaluateJavascript @ [publib]:454
handleProcessMessage @ [publib]:786
ws.on @ [publib]:901
emitOne @ events.js:115
emit @ events.js:210
_receiver.onmessage @ C:\Program Files (x86)\Tencent\微信web开发者工具\package.nw\node_modules\ws\lib\WebSocket.js:141
dataMessage @ C:\Program Files (x86)\Tencent\微信web开发者工具\package.nw\node_modules\ws\lib\Receiver.js:389
getData @ C:\Program Files (x86)\Tencent\微信web开发者工具\package.nw\node_modules\ws\lib\Receiver.js:330
startLoop @ C:\Program Files (x86)\Tencent\微信web开发者工具\package.nw\node_modules\ws\lib\Receiver.js:165
add @ C:\Program Files (x86)\Tencent\微信web开发者工具\package.nw\node_modules\ws\lib\Receiver.js:139
_ultron.on @ C:\Program Files (x86)\Tencent\微信web开发者工具\package.nw\node_modules\ws\lib\WebSocket.js:138
emitOne @ events.js:115
emit @ events.js:210
addChunk @ _stream_readable.js:263
readableAddChunk @ _stream_readable.js:250
Readable.push @ _stream_readable.js:208
onread @ net.js:595
[publib]:3 appServiceSDKScriptError
Converting circular structure to JSON; at wx.invokeWebviewMethod
TypeError: Converting circular structure to JSON
    at stringify (<anonymous>)
    at Object.w [as publish] ([publib]:1:1504)
    at i ([publib]:4:4670)
    at Function.l ([publib]:10:3109)
    at Object.<anonymous> ([publib]:4:9812)
    at Function.value ([publib]:18:8620)
    at e.value ([publib]:18:6008)
    at weapp:///static/js/vendor.js:5002:9
    at weapp:///static/js/vendor.js:4988:27
    at Vue$3.updateDataToMP [as $updateDataToMP] (weapp:///static/js/vendor.js:5026:9)

这时退出裁剪页面，再次进入裁剪页面，裁剪页面裁剪框无法显示，选择图片不显示
@dlhandsome 能否看一下这个问题呢，谢谢

**Comment by dlhandsome** [comment]
f625af4
``` bash
 npm install mpvue-cropper@0.08 --save-dev
```

**Comment by williamJson** [comment]
刚试了一下，貌似还是不行，错误和昨天一样

**Comment by dlhandsome** [comment]
https://github.com/we-plugin/we-cropper/commit/8b9ea38f3f20554fe3a78239759b11303e92b570
