### ISSUE TITLE
[Feature Request] we-cropper在mpvue中截图模糊问题

### ISSUE THREAD

**Issue by ChengYu-Zhang** [we-plugin/we-cropper#74]
### 描述
we-cropper在mpvue中怎样优化截图模糊问题呢？

**Comment by ChengYu-Zhang** [comment]
we-cropper在mpvue中怎样优化截图模糊问题呢？

**Comment by dlhandsome** [comment]
https://github.com/we-plugin/we-cropper/wiki/FAQ

**Comment by ChengYu-Zhang** [comment]
在mpvue中
let { imgLeft, imgTop, scaleWidth, scaleHeight } = this.wecropper
let { x, y, width, height } = this.wecropper.cut
获取不到相应的参数，怎样才能获取参数呢

**Comment by ChengYu-Zhang** [comment]
您那边封装好的组件吗？因为我这边赶项目没有时间自己封装，如果有麻烦您给我分享一下，万分感谢~

**Comment by ReggieCai31** [comment]
> 在mpvue中
> let { imgLeft, imgTop, scaleWidth, scaleHeight } = this.wecropper
> let { x, y, width, height } = this.wecropper.cut
> 获取不到相应的参数，怎样才能获取参数呢

同样的疑问

**Comment by zhangkaicheng521** [comment]
> 在mpvue中
> let { imgLeft, imgTop, scaleWidth, scaleHeight } = this.wecropper
> let { x, y, width, height } = this.wecropper.cut
> 获取不到相应的参数，怎样才能获取参数呢

请问这个问题解决了吗？我也遇到了

**Comment by dlhandsome** [comment]
https://github.com/we-plugin/we-cropper/pull/88
