### ISSUE TITLE
旋转加裁剪问题，描述如下：

### ISSUE THREAD

**Issue by UprightCedar** [we-plugin/we-cropper#76]
项目需要，上传身份证，然后要添加旋转功能（点按钮每次旋转90c），画布上图片的宽度是固定值（750rpx），高度自适应，旋转后图片的高变成宽，另一边自适应，我在你的源码中改了一下，修改如下： 
![image](https://user-images.githubusercontent.com/30796282/45345542-36fed080-b5d9-11e8-83b3-bdb224f77498.png)

> // 图片旋转 点击事件
  rotateImg() {
    const self = this;
    let rotateI = this.data.rotateI + 1;
    this.setData({
      rotateI: rotateI
    })
    self.wecropper.updateCanvas(rotateI)
  }

> 源码修改：self.updateCanvas = function (rotateI) {
      self.rotateI = rotateI ? rotateI : self.rotateI
      if (self.croperTarget) {
        //  画布绘制图片
        self.ctx.save()
        self.ctx.translate(boundWidth / 2, boundHeight/2)
        self.ctx.rotate(self.rotateI*Math.PI / 180*90)
        if (self.rotateI%2 == 1 ) {
            self.ctx.drawImage(self.croperTarget, self.imgTop - ref.y, self.imgLeft - self.scaleWidth / 2, self.scaleWidth * self.scaleWidth / self.scaleHeight, self.scaleWidth);
        } else {
        self.ctx.drawImage(self.croperTarget, self.imgLeft - self.scaleWidth / 2, self.imgTop - ref.y * 2, self.scaleWidth, self.scaleHeight);
        self.ctx.drawImage(self.croperTarget, self.imgLeft, self.imgTop, self.scaleWidth, self.scaleHeight);
         }
        self.ctx.restore()
      }
      
      isFunction(self.onBeforeDraw) && self.onBeforeDraw(self.ctx, self);
      self.setBoundStyle(); //	设置边界样式
      self.ctx.draw();
      return self
    };

这是最接近成功的一次，有如下问题：图片宽度大于高度时，且高度小于裁剪框高度时，图片旋转后，图片会出现在裁剪框之外，而且怎么移动都不能移入裁剪框内（这个应该是旋转后图片宽高变化导致边界的限制），旋转后移动事件正好是相反的

随后又尝试了在创建canvas时就移动canvas的原点坐标
然后裁剪框是正常的
![image](https://user-images.githubusercontent.com/30796282/45346585-24d26180-b5dc-11e8-9ba0-0ac4dfe35036.png)

选择图片后：
![image](https://user-images.githubusercontent.com/30796282/45346619-3c114f00-b5dc-11e8-958e-fc6279c1de0e.png)

歪了。。。
请教大佬这个该怎么弄一下呢

**Comment by dlhandsome** [comment]
重新按照规范提交一下issue吧
