### ISSUE TITLE
[Bug Report] 小程序插件内部无法使用we-cropper

### ISSUE THREAD

**Issue by chris-fung** [we-plugin/we-cropper#78]
### we-cropper 版本
1.2.0

### 对应工具或者iOS或者Andriod的版本号
Android 7

### 微信版本号
6.6.7

### 重现步骤
在小程序插件内部的页面，点击按钮触发wx.chooseImage选择图片成功后导航到we-cropper页面

### 期待的行为
点击上传图片之后，能够正常显示裁剪框

### 实际的行为
canvas没有渲染出图片和裁剪框。

**Comment by 392736970** [comment]
您好，请问解决了吗

**Comment by dlhandsome** [comment]
已支持小程序自定义组件 https://github.com/we-plugin/we-cropper/tree/master/packages/miniprogram-cropper
