### ISSUE TITLE
[Feature Request] 提供获取CDN（云存储）的裁剪参数的方法

### ISSUE THREAD

**Issue by cleocn** [we-plugin/we-cropper#82]
### 描述
现在提供的是获取一个裁剪完成的本地地址。
但我们不在本地直接裁剪，而是上传原图，然后通过设置cdn的链接裁剪参数来完成自动的裁剪。这样在裁剪时候，无需多次上传。

**Comment by dlhandsome** [comment]
可以通过实例拿到裁剪参数
