### ISSUE TITLE
[Bug Report] 截图不清晰，使用faq方法也有问题

### ISSUE THREAD

**Issue by NewbMiao** [we-plugin/we-cropper#87]
### we-cropper 版本
0.1.0

### 对应工具或者iOS或者Andriod的版本号
8.0.0

### 微信版本号
6.7.3

### 重现步骤
使用https://github.com/we-plugin/we-cropper/wiki/FAQ
中btnHandle ，target的隐藏画布宽高还是设置为cropperOpt里的设备宽高，截图会变大
但如果devicePixelRatio设置为1，效果反而会变好一点。（用有字的图片对比）

按理这样和源码getCropperImage不应该一致么，为啥会更清晰一点

### 期待的行为
截图清晰，将devicePixelRatio设置为1是否可行

### 实际的行为
截图不清晰

**Comment by 1c7** [comment]
截图不清晰+1

**Comment by zhangkaicheng521** [comment]
mpvue  怎么解决截图不清晰问题呀。
 let { imgLeft, imgTop, scaleWidth, scaleHeight } = wecropper   获取不到

**Comment by waynecz** [comment]
附议

**Comment by 1c7** [comment]
比较急的同学可以参考这篇文章（我写的）: https://1c7.me/2018-12-25-wechat-miniapp-image-crop/
或者尝试按照 FAQ 里的做法自己写一点代码：https://github.com/we-plugin/we-cropper/wiki/FAQ

we-cropper 的微信群里有同学说按照 FAQ 里的做法管用

**Comment by waynecz** [comment]
@1c7 感谢层主！

**Comment by 1c7** [comment]
@waynecz  咦？你在饿了吗做小程序啊？

**Comment by dlhandsome** [comment]
https://github.com/we-plugin/we-cropper/pull/88

**Comment by 1c7** [comment]
感谢 @dlhandsome
