### ISSUE TITLE
[Bug Report]组件中使用时因为上下文不对，获取不到指定Canvas上下文

### ISSUE THREAD

**Issue by JaxXu** [we-plugin/we-cropper#94]
### 描述
组件中使用时因为上下文不对，获取不到指定Canvas上下文

**Comment by JaxXu** [comment]
留坑待PR，勿删

**Comment by dlhandsome** [comment]
https://github.com/we-plugin/we-cropper/tree/master/packages/miniprogram-cropper

已支持原生自定义组件

canvas 上下文也已支持 https://github.com/we-plugin/we-cropper/pull/110
